services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    volumes: 
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
    restart: on-failure
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres:

# docker compose up -sobre o banco
# docker ps -lista os containers